import { SurveyForm } from "../model/surveyFormModel";
// import { Voters } from "../model/votersModel";
// import { Leader } from "../model/collectionModel";
import ABELLA from "../assets/candidates/abella.png";
import DE_GUZMAN from "../assets/candidates/DE GUZMAN.png";
import DOMAGOSO from "../assets/candidates/DOMAGOSO.png";
import LACSON from "../assets/candidates/LACSON.png";
import GONZALES from "../assets/candidates/GONZALES.png";
import MONTEMAYOR from "../assets/candidates/MONTEMAYOR.png";
import MANGONDATO from "../assets/candidates/MANGONDATO.png";
import ROBREDO from "../assets/candidates/ROBREDO.png";
import PACQUIAO from "../assets/candidates/PAQUIO.png";
import MARCOS from "../assets/candidates/MARCOS.png";

export const SURVEY_FORM: SurveyForm[] = [
  {
    id: "FORM_1",
    title: "Barangay Official Election Voting Form",
    access: "public",
    image: null,
    logo: null,
    banner: null,
    status: "open",
    link: "https://www.google.com",
    short_desc: "2024 Election Survey",
    long_desc: `Please fill out this form to cast your vote for the Barangay Officials. Each voter is allowed to vote only once.`,
    author: "John Doe",
    date: "2022-10-10",
    questions: [
      {
        id: "QUESTION_1",
        type: "short_answer",
        title: "Full Name",
        placeholder: "Enter your fullname",
        choices: null,
        required: true,
      },
      // {
      //   id: "QUESTION_2",
      //   type: "short_answer",
      //   title: "Email",
      //   placeholder: "Enter your email",
      //   choices: null,
      //   required: true,
      // },
      // {
      //   id: "QUESTION_3",
      //   type: "dropdown",
      //   title: "Barangay",
      //   placeholder: null,
      //   choices: [
      //     {
      //       id: "0",
      //       label: "VILLA NAVA",
      //       image: null,
      //     },
      //     {
      //       id: "1",
      //       label: "RIZAL",
      //       image: null,
      //     },
      //     {
      //       id: "2",
      //       label: "VILLA PADUA",
      //       image: null,
      //     },
      //   ],
      //   required: false,
      // },
      // {
      //   id: "QUESTION_2",
      //   type: "paragraph",
      //   title: "Describe yourself?",
      //   placeholder: "Enter your description",
      //   choices: null,
      //   required: true,
      // },

      // {
      //   id: "QUESTION_4",
      //   type: "multiple_choice",
      //   title: " Who is your Barangay Captain ",
      //   placeholder: null,
      //   choices: [
      //     {
      //       id: "0",
      //       label: "SALUME, JOSE",
      //       image: "test.png",
      //     },
      //     {
      //       id: "1",
      //       label: "MAGSAYSAY, RAMON ",
      //       image: "test.png",
      //     },
      //     {
      //       id: "2",
      //       label: "GOU, ALESIO",
      //       image: "test.png",
      //     },
      //     {
      //       id: "3",
      //       label: "DEL CARMEN, FERDENAND",
      //       image: "test.png",w
      //     },
      //   ],
      //   required: true,
      // },
      {
        id: "QUESTION_2",
        type: "multiple_choice_grid_categories",
        title:
          " Choose one candidate only by clicking the circle box next to the candidate name then click submit to save your vote.",
        placeholder: null,
        choices: [
          {
            id: "Q4_1",
            label: "Abella, Ernie",
            category: "INDEPENDENT",
            image: ABELLA,
          },
          {
            id: "Q4_2",
            label: "De Guzman, Leody",
            category: "PARTIDO LAKAS NG MASA",
            image: DE_GUZMAN,
          },
          {
            id: "Q4_3",
            label: "Domagoso, Isko Moreno",
            category: "AKSYON DEMOKRATIKO",
            image: DOMAGOSO,
          },
          {
            id: "Q4_4",
            label: "Gonzales, Norberto",
            category: "PARTIDO DEMOKTRATIKO SOSYALISTA PILIPINAS",
            image: GONZALES,
          },
          {
            id: "Q4_5",
            label: "Lacson, Ping",
            category: "INDEPENDENT",
            image: LACSON,
          },
          {
            id: "Q4_6",
            label: "Mangondato, Faisal",
            category: "KATIPUNAN NG KAMALAYANG KAYUMANGGI",
            image: MANGONDATO,
          },
          {
            id: "Q4_7",
            label: "Marcos, Bongbong",
            category: "PARTIDO FEDERAL NG PILIPINAS",
            image: MARCOS,
          },
          {
            id: "Q4_8",
            label: "Montemayor, Jose Jr.",
            category: "INDEPENDENT",
            image: MONTEMAYOR,
          },
          {
            id: "Q4_9",
            label: "Pacquiao, Manny Pacman",
            category: "ABAG PROMDI",
            image: PACQUIAO,
          },
          {
            id: " Q4_10",
            label: "Robredo, Leni ",
            category: "INDEPENDENT",
            image: ROBREDO,
          },
        ],
        required: true,
      },
      {
        id: "QUESTION_3",
        type: "checkboxes",
        title: " Who is your Barangay Councilor?",
        placeholder: null,
        choices: [
          {
            id: "0",
            label: "LUNA, ANTHONY",
            image: null,
          },
          {
            id: "1",
            label: "RIZAL, JOSELINE",
            image: null,
          },
          {
            id: "2",
            label: "LAPUZ, LAPPEZ",
            image: null,
          },
          {
            id: "3",
            label: "DEL CARMEN, FERDENAND",
            image: null,
          },
          {
            id: "8",
            label: "DEL CARMEN, FERDENAND",
            image: null,
          },
          {
            id: "4",
            label: "SALUME, JOSE",
            image: null,
          },
          {
            id: "5",
            label: "MAGSAYSAY, RAMON ",
            image: null,
          },
          {
            id: "6",
            label: "GOU, ALESIO",
            image: null,
          },
          {
            id: "7",
            label: "DE MARIA, JOSEPH",
            image: null,
          },
        ],
        required: true,
      },

      {
        id: "QUESTION_4",
        type: "linear_scale",
        title: "How satisfied were you with the overall election process?",
        placeholder: null,
        choices: [
          {
            id: "0",
            label: "Very Dissatisfied",
            image: null,
          },
          {
            id: "1",
            label: "Dissatisfied",
            image: null,
          },
          {
            id: "2",
            label: "Neutral",
            image: null,
          },
          {
            id: "3",
            label: "Satisfied",
            image: null,
          },
          {
            id: "4",
            label: "Very Satisfied",
            image: null,
          },
        ],
        required: true,
      },
    ],
  },
  // {
  //   id: "FORM_2",
  //   title: "Barangay Official Election Voting Form (Test)",
  //   access: "public",
  //   image: null,
  //   logo: null,
  //   banner: null,
  //   status: "open",
  //   link: "https://www.google.com",
  //   short_desc: "2024 Election Survey",
  //   long_desc: `Please fill out this form to cast your vote for the Barangay Officials. Each voter is allowed to vote only once.`,
  //   author: "John Doe",
  //   date: "2022-10-10",
  //   questions: [
  //     {
  //       id: "QUESTION_1",
  //       type: "short_answer",
  //       title: "Full Name",
  //       placeholder: "Enter your fullname",
  //       choices: null,
  //       required: true,
  //     },
  //     {
  //       id: "QUESTION_2",
  //       type: "short_answer",
  //       title: "Email",
  //       placeholder: "Enter your email",
  //       choices: null,
  //       required: true,
  //     },
  //     {
  //       id: "QUESTION_3",
  //       type: "dropdown",
  //       title: "Barangay",
  //       placeholder: null,
  //       choices: [
  //         {
  //           id: "0",
  //           label: "VILLA NAVA",
  //           image: null,
  //         },
  //         {
  //           id: "1",
  //           label: "RIZAL",
  //           image: null,
  //         },
  //         {
  //           id: "2",
  //           label: "VILLA PADUA",
  //           image: null,
  //         },
  //       ],
  //       required: false,
  //     },
  //     {
  //       id: "QUESTION_2",
  //       type: "paragraph",
  //       title: "Describe yourself?",
  //       placeholder: "Enter your description",
  //       choices: null,
  //       required: true,
  //     },

  //     {
  //       id: "QUESTION_4",
  //       type: "multiple_choice",
  //       title: " Who is your Barangay Captain ",
  //       placeholder: null,
  //       choices: [
  //         {
  //           id: "0",
  //           label: "SALUME, JOSE",
  //           image: "test.png",
  //         },
  //         {
  //           id: "1",
  //           label: "MAGSAYSAY, RAMON ",
  //           image: "test.png",
  //         },
  //         {
  //           id: "2",
  //           label: "GOU, ALESIO",
  //           image: "test.png",
  //         },
  //         {
  //           id: "3",
  //           label: "DEL CARMEN, FERDENAND",
  //           image: "test.png",
  //         },
  //       ],
  //       required: true,
  //     },
  //     {
  //       id: "QUESTION_2",
  //       type: "multiple_choice_grid_categories",
  //       title:
  //         " Choose one candidate only by clicking the circle box next to the candidate name then click submit to save your vote.",
  //       placeholder: null,
  //       choices: [
  //         {
  //           id: "Q4_1",
  //           label: "Abella, Ernie",
  //           category: "INDEPENDENT",
  //           image: ABELLA,
  //         },
  //         {
  //           id: "Q4_2",
  //           label: "De Guzman, Leody",
  //           category: "PARTIDO LAKAS NG MASA",
  //           image: DE_GUZMAN,
  //         },
  //         {
  //           id: "Q4_3",
  //           label: "Domagoso, Isko Moreno",
  //           category: "AKSYON DEMOKRATIKO",
  //           image: DOMAGOSO,
  //         },
  //         {
  //           id: "Q4_4",
  //           label: "Gonzales, Norberto",
  //           category: "PARTIDO DEMOKTRATIKO SOSYALISTA PILIPINAS",
  //           image: GONZALES,
  //         },
  //         {
  //           id: "Q4_5",
  //           label: "Lacson, Ping",
  //           category: "INDEPENDENT",
  //           image: LACSON,
  //         },
  //         {
  //           id: "Q4_6",
  //           label: "Mangondato, Faisal",
  //           category: "KATIPUNAN NG KAMALAYANG KAYUMANGGI",
  //           image: MANGONDATO,
  //         },
  //         {
  //           id: "Q4_7",
  //           label: "Marcos, Bongbong",
  //           category: "PARTIDO FEDERAL NG PILIPINAS",
  //           image: MARCOS,
  //         },
  //         {
  //           id: "Q4_8",
  //           label: "Montemayor, Jose Jr.",
  //           category: "INDEPENDENT",
  //           image: MONTEMAYOR,
  //         },
  //         {
  //           id: "Q4_9",
  //           label: "Pacquiao, Manny Pacman",
  //           category: "ABAG PROMDI",
  //           image: PACQUIAO,
  //         },
  //         {
  //           id: " Q4_10",
  //           label: "Robredo, Leni ",
  //           category: "INDEPENDENT",
  //           image: ROBREDO,
  //         },
  //       ],
  //       required: true,
  //     },
  //     {
  //       id: "QUESTION_3",
  //       type: "checkboxes",
  //       title: " Who is your Barangay Councilor?",
  //       placeholder: null,
  //       choices: [
  //         {
  //           id: "0",
  //           label: "LUNA, ANTHONY",
  //           image: null,
  //         },
  //         {
  //           id: "1",
  //           label: "RIZAL, JOSELINE",
  //           image: null,
  //         },
  //         {
  //           id: "2",
  //           label: "LAPUZ, LAPPEZ",
  //           image: null,
  //         },
  //         {
  //           id: "3",
  //           label: "DEL CARMEN, FERDENAND",
  //           image: null,
  //         },
  //         {
  //           id: "8",
  //           label: "DEL CARMEN, FERDENAND",
  //           image: null,
  //         },
  //         {
  //           id: "4",
  //           label: "SALUME, JOSE",
  //           image: null,
  //         },
  //         {
  //           id: "5",
  //           label: "MAGSAYSAY, RAMON ",
  //           image: null,
  //         },
  //         {
  //           id: "6",
  //           label: "GOU, ALESIO",
  //           image: null,
  //         },
  //         {
  //           id: "7",
  //           label: "DE MARIA, JOSEPH",
  //           image: null,
  //         },
  //       ],
  //       required: true,
  //     },

  //     {
  //       id: "QUESTION_4",
  //       type: "linear_scale",
  //       title: "How satisfied were you with the overall election process?",
  //       placeholder: null,
  //       choices: [
  //         {
  //           id: "0",
  //           label: "Very Dissatisfied",
  //           image: null,
  //         },
  //         {
  //           id: "1",
  //           label: "Dissatisfied",
  //           image: null,
  //         },
  //         {
  //           id: "2",
  //           label: "Neutral",
  //           image: null,
  //         },
  //         {
  //           id: "3",
  //           label: "Satisfied",
  //           image: null,
  //         },
  //         {
  //           id: "4",
  //           label: "Very Satisfied",
  //           image: null,
  //         },
  //       ],
  //       required: true,
  //     },
  //   ],
  // },
];

// export const events: Event[] = [
//   {
//     id: "event1",
//     name: "𝐕𝐞𝐧𝐝𝐨𝐫𝐬 𝐀𝐬𝐬𝐨𝐜𝐢𝐚𝐭𝐢𝐨𝐧 𝐌𝐞𝐞𝐭𝐢𝐧𝐠 ",
//     description: `Si 𝐏𝐮𝐧𝐨𝐧𝐠 𝐁𝐚𝐫𝐚𝐧𝐠𝐚𝐲 𝐌𝐢𝐤𝐨 𝐕𝐢𝐥𝐥𝐞𝐧𝐚 𝐚𝐭 𝐚𝐧𝐠 𝐤𝐨𝐧𝐬𝐞𝐡𝐨 ay nagdaos ng 𝐕𝐞𝐧𝐝𝐨𝐫𝐬 𝐀𝐬𝐬𝐨𝐜𝐢𝐚𝐭𝐢𝐨𝐧 𝐌𝐞𝐞𝐭𝐢𝐧𝐠 kahapon, kung saan dinaluhan ito nina 𝐂𝐨𝐧𝐠𝐫𝐞𝐬𝐬𝐦𝐚𝐧 𝐋𝐮𝐢𝐬 𝐂𝐚𝐦𝐩𝐨𝐬 𝐚𝐭 𝐂𝐨𝐧𝐠𝐫𝐞𝐬𝐬𝐦𝐚𝐧 𝐊𝐢𝐝 𝐏𝐞ñ𝐚.
// Ang layunin ng pagpupulong ay talakayin ang mga hinaing at pangangailangan ng mga tindero at tindera sa ating barangay at lumikha ng mga konkretong hakbang para mas mapabuti ang kanilang paghahanapbuhay.`,
//     date: "2024-08-01",
//     startTime: "08:00",
//     endTime: "12:00", // Adjust according to actual end time
//     location: [
//       {
//         country: "Philippines",
//         region: "Region",
//         province: "Province",
//         city: "City",
//         district: "District",
//         barangay: "Barangay",
//         street: "Various Polling Stations",
//         period: {
//           start: "2024-08-01T08:00:00Z",
//           end: "2024-08-01T12:00:00Z",
//         },
//       },
//     ],
//     coverPhoto: VAM,
//     photos: ["path/to/photo1.jpg", "path/to/photo2.jpg"], // Add paths to photos if available
//     leaders: ["0", "1"],
//     category: "Meeting",
//     link: "https://www.facebook.com/share/p/cBGP4FgPQsSt58h4/",
//     expenses: 10299,
//     status: "active",
//   },
//   {
//     id: "event2",
//     name: "Barangay Regular Monthly Meeting",
//     description: "Liga ng mga Barangay Regular Monthly Meeting",
//     date: "2024-08-01",
//     startTime: "08:00",
//     endTime: "12:00", // Adjust according to actual end time
//     location: [
//       {
//         country: "Philippines",
//         region: "Region",
//         province: "Province",
//         city: "City",
//         district: "District",
//         barangay: "Barangay",
//         street: "Various Polling Stations",
//         period: {
//           start: "2024-08-01T08:00:00Z",
//           end: "2024-08-01T12:00:00Z",
//         },
//       },
//     ],
//     coverPhoto: BRM,
//     photos: ["path/to/photo1.jpg", "path/to/photo2.jpg"], // Add paths to photos if available
//     leaders: ["1", "0"],
//     category: "Election",
//     link: "http://example.com/localcouncilelections",
//     expenses: 500000,
//     status: "done",
//   },
//   {
//     id: "event3",
//     name: "Referendum on New Policies",
//     description: "Vote on proposed new policies affecting the community.",
//     date: "2024-12-10",
//     startTime: "08:00",
//     endTime: "12:00", // Adjust according to actual end time
//     location: [
//       {
//         country: "Philippines",
//         region: "Region",
//         province: "Province",
//         city: "City",
//         district: "District",
//         barangay: "Barangay",
//         street: "Community Centers",
//         period: {
//           start: "2024-12-10T08:00:00Z",
//           end: "2024-12-10T12:00:00Z",
//         },
//       },
//     ],
//     coverPhoto: "",
//     photos: [], // Add paths to photos if available
//     leaders: ["0"],
//     category: "Voting",
//     link: "http://example.com/referendum",
//     expenses: 300000,
//     status: "done",
//   },
//   {
//     id: "event4",
//     name: "SK Election Meeting",
//     description: "Election for the Senate seats.",
//     date: "2024-08-10",
//     startTime: "08:00",
//     endTime: "12:00", // Adjust according to actual end time
//     location: [
//       {
//         country: "Philippines",
//         region: "Region",
//         province: "Province",
//         city: "City",
//         district: "District",
//         barangay: "Barangay",
//         street: "Various Polling Stations",
//         period: {
//           start: "2024-08-10T08:00:00Z",
//           end: "2024-08-10T12:00:00Z",
//         },
//       },
//     ],
//     coverPhoto: BH,
//     photos: ["path/to/photo1.jpg", "path/to/photo2.jpg"], // Add paths to photos if available
//     leaders: ["1"],
//     category: "Election",
//     link: "http://example.com/senateelection",
//     expenses: 800000,
//     status: "cancelled",
//   },
//   {
//     id: "event5",
//     name: "City Mayoral Election",
//     description: "Election to choose the Mayor of the city.",
//     date: "2024-10-25",
//     startTime: "08:00",
//     endTime: "12:00", // Adjust according to actual end time
//     location: [
//       {
//         country: "Philippines",
//         region: "Region",
//         province: "Province",
//         city: "City",
//         district: "District",
//         barangay: "Barangay",
//         street: "City Hall and Other Polling Stations",
//         period: {
//           start: "2024-10-25T08:00:00Z",
//           end: "2024-10-25T12:00:00Z",
//         },
//       },
//     ],
//     coverPhoto: "",
//     photos: [], // Add paths to photos if available
//     leaders: ["1"],
//     category: "Election",
//     link: "http://example.com/citymayoralelection",
//     expenses: 400000,
//     status: "pending",
//   },
//   {
//     id: "event6",
//     name: "KK (Katipunan ng Kabataan)",
//     description: `‼️𝘼𝙉𝙉𝙊𝙐𝙉𝘾𝙀𝙈𝙀𝙉𝙏‼️
// 𝙏𝙝𝙚 𝙎𝘼𝙉𝙂𝙂𝙐𝙉𝙄𝘼𝙉𝙂 𝙆𝘼𝘽𝘼𝙏𝘼𝘼𝙉 𝙉𝙂 𝘽𝘼𝙍𝘼𝙉𝙂𝘼𝙔  JAO-ASAN  𝙬𝙞𝙡𝙡 𝙗𝙚 𝙘𝙤𝙣𝙙𝙪𝙘𝙩𝙞𝙣𝙜 𝙖 Second  (2nd) Quarter 𝙆𝙆  (𝙆𝙖𝙩𝙞𝙥𝙪𝙣𝙖𝙣 𝙣𝙜 𝙆𝙖𝙗𝙖𝙩𝙖𝙖𝙣) 𝙢𝙚𝙚𝙩𝙞𝙣𝙜:
// 📌𝙒𝙝𝙖𝙩:Second (2nd) Quarter Katipunan ng Kabataan (KK) General Assembly
// 📌𝙒𝙝𝙚𝙣: August 10, 2024 at 1:00 pm onwards
// 📌𝙒𝙝𝙤: All youth aged 15 to 30 of Barangay Jao-asan
// 📌𝙒𝙝𝙚𝙧𝙚: Sitio Proper, Jao-asan  Covered Court
// ✨Isang mapagpalang araw po sa inyong lahat! Kami po na mga Sangguniang Kabataan Officials ay ikinagagalak na ipaalam sa inyo na magkakaroon po tayo ng 2nd Quarter KK Meeting.✨
// Makialam at Makiisa!
// See you there everyone! ❤️`,
//     date: "2024-08-10",
//     startTime: "13:00",
//     endTime: "18:00", // Adjust according to actual end time
//     location: [
//       {
//         country: "Philippines",
//         region: "Region",
//         province: "Province",
//         city: "City",
//         district: "District",
//         barangay: "Barangay",
//         street: "Community Centers",
//         period: {
//           start: "2024-08-10T13:00:00Z",
//           end: "2024-08-10T18:00:00Z",
//         },
//       },
//     ],
//     coverPhoto: "",
//     photos: ["path/to/photo1.jpg", "path/to/photo2.jpg"], // Add paths to photos if available
//     leaders: ["0"],
//     category: "Meeting",
//     link: "http://example.com/referendum",
//     expenses: 60000,
//     status: "done",
//   },
// ];

// export const sampleData: Attendance[] = [
//   {
//     id: "1",
//     voterId: "0",
//     eventId: "event1",
//     date: "2024-08-04",
//     timeIn: "09:00",
//     timeOut: "17:00",
//     scannedBy: "scanner01",
//     status: "present",
//     duration: "8h",
//     expenses: 100,
//   },
//   {
//     id: "1",
//     voterId: "0",
//     eventId: "event1",
//     date: "2024-08-04",
//     timeIn: "09:00",
//     timeOut: "17:00",
//     scannedBy: "scanner01",
//     status: "present",
//     duration: "8h",
//     expenses: 100,
//   },
//   {
//     id: "1",
//     voterId: "0",
//     eventId: "event1",
//     date: "2024-08-04",
//     timeIn: "09:00",
//     timeOut: "17:00",
//     scannedBy: "scanner01",
//     status: "present",
//     duration: "8h",
//     expenses: 100,
//   },
//   {
//     id: "1",
//     voterId: "0",
//     eventId: "event1",
//     date: "2024-08-04",
//     timeIn: "09:00",
//     timeOut: "17:00",
//     scannedBy: "scanner01",
//     status: "present",
//     duration: "8h",
//     expenses: 100,
//   },
//   {
//     id: "1",
//     voterId: "0",
//     eventId: "event1",
//     date: "2024-08-04",
//     timeIn: "09:00",
//     timeOut: "17:00",
//     scannedBy: "scanner01",
//     status: "present",
//     duration: "8h",
//     expenses: 100,
//   },
//   {
//     id: "1",
//     voterId: "0",
//     eventId: "event2",
//     date: "2024-08-04",
//     timeIn: "09:00",
//     timeOut: "17:00",
//     scannedBy: "scanner01",
//     status: "present",
//     duration: "8h",
//     expenses: 100,
//   },
// ];

// export const samplePerson: Person[] = [
//   {
//     id: "0",
//     customId: "PH-2024-0001",
//     precinct: {
//       id: "precinct-001",
//       name: "Precinct 1",
//       adress: [
//         {
//           use: "work",
//           type: "physical",
//           text: "Municipal Hall, Alicia, Quezon City, Metro Manila, Philippines",
//           line: ["Municipal Hall", "Alicia"],
//           country: "Philippines",
//           region: "NCR",
//           province: "Metro Manila",
//           city: "Quezon City",
//           district: "4th District",
//           barangay: "Alicia",
//           street: "Government St",
//           purok: "Purok 2",
//           sitio: "Sitio Example",
//           overpass: [["overpass 1", "overpass 2"]],
//           long: 121.0437,
//           lat: 14.676,
//           zipcode: "1100",
//           postalCode: "1100",
//           period: {
//             start: "2010-01-01",
//             end: "2024-12-31",
//           },
//         },
//       ],
//       cluster: "Cluster A",
//     },
//     photo: PACQUIAO,
//     name: {
//       firstname: "Juan",
//       lastname: "Dela Cruz",
//       middlename: "Santos",
//       suffix: "Jr.",
//       prefix: "Mr.",
//       degree: "Bachelor of Science",
//     },
//     address: [
//       {
//         use: "home",
//         type: "physical",
//         text: "123 Example St, Alicia, Quezon City, Metro Manila, Philippines",
//         line: ["123 Example St", "Alicia"],
//         country: "Philippines",
//         region: "NCR",
//         province: "Metro Manila",
//         city: "Quezon City",
//         district: "4th District",
//         barangay: "Alicia",
//         street: "Example St",
//         purok: "Purok 1",
//         sitio: "Sitio Example",
//         overpass: [["overpass 1", "overpass 2"]],
//         long: 121.0437,
//         lat: 14.676,
//         zipcode: "1100",
//         postalCode: "1100",
//         period: {
//           start: "2010-01-01",
//           end: "2024-12-31",
//         },
//       },
//     ],
//     contact: "+639171234567",
//     email: "juan.delacruz@example.com",
//     birthday: "1990-01-01",
//     age: 34,
//     sex: "male",
//     status: "active",
//     role: "viewer",
//     type: "leader",
//     category: "voter",
//   },
//   {
//     id: "1",
//     customId: "PH-2024-0003",
//     precinct: {
//       id: "precinct-003",
//       name: "Precinct 3",
//       adress: [
//         {
//           use: "work",
//           type: "physical",
//           text: "Community Center, Bagong Pag-asa, Manila, Metro Manila, Philippines",
//           line: ["Community Center", "Bagong Pag-asa"],
//           country: "Philippines",
//           region: "NCR",
//           province: "Metro Manila",
//           city: "Manila",
//           district: "5th District",
//           barangay: "Bagong Pag-asa",
//           street: "Main St",
//           purok: "Purok 5",
//           sitio: "Sitio Example3",
//           overpass: [["overpass 5", "overpass 6"]],
//           long: 120.9876,
//           lat: 14.5995,
//           zipcode: "1000",
//           postalCode: "1000",
//           period: {
//             start: "2014-03-03",
//             end: "2024-12-31",
//           },
//         },
//       ],
//       cluster: "Cluster C",
//     },
//     photo: "",
//     name: {
//       firstname: "Jose",
//       lastname: "Rizal",
//       middlename: "Mercado",
//       suffix: "",
//       prefix: "Dr.",
//       degree: "Doctor of Medicine",
//     },
//     address: [
//       {
//         use: "home",
//         type: "physical",
//         text: "789 Example3 St, Alicia, Manila, Metro Manila, Philippines",
//         line: ["789 Example3 St", "Alicia"],
//         country: "Philippines",
//         region: "NCR",
//         province: "Metro Manila",
//         city: "Quezon City",
//         district: "5th District",
//         barangay: "Alicia",
//         street: "Example3 St",
//         purok: "Purok 6",
//         sitio: "Sitio Example3",
//         overpass: [["overpass 7", "overpass 8"]],
//         long: 120.9876,
//         lat: 14.5995,
//         zipcode: "1000",
//         postalCode: "1000",
//         period: {
//           start: "2014-03-03",
//           end: "2024-12-31",
//         },
//       },
//     ],
//     contact: "+639181234569",
//     email: "jose.rizal@example.com",
//     birthday: "1970-03-03",
//     age: 54,
//     sex: "male",
//     status: "inactive",
//     role: "viewer",
//     type: "member",
//     category: "voter",
//   },
//   {
//     id: "2",
//     customId: "PH-2024-0003",
//     precinct: {
//       id: "precinct-003",
//       name: "Precinct 3",
//       adress: [
//         {
//           use: "work",
//           type: "physical",
//           text: "Community Center, Bagong Pag-asa, Manila, Metro Manila, Philippines",
//           line: ["Community Center", "Bagong Pag-asa"],
//           country: "Philippines",
//           region: "NCR",
//           province: "Metro Manila",
//           city: "Manila",
//           district: "5th District",
//           barangay: "Bagong Pag-asa",
//           street: "Main St",
//           purok: "Purok 5",
//           sitio: "Sitio Example3",
//           overpass: [["overpass 5", "overpass 6"]],
//           long: 120.9876,
//           lat: 14.5995,
//           zipcode: "1000",
//           postalCode: "1000",
//           period: {
//             start: "2014-03-03",
//             end: "2024-12-31",
//           },
//         },
//       ],
//       cluster: "Cluster C",
//     },
//     photo: "",
//     name: {
//       firstname: "Jose",
//       lastname: "Rizal",
//       middlename: "Mercado",
//       suffix: "",
//       prefix: "Dr.",
//       degree: "Doctor of Medicine",
//     },
//     address: [
//       {
//         use: "home",
//         type: "physical",
//         text: "789 Example3 St, Bagong Pag-asa, Manila, Metro Manila, Philippines",
//         line: ["789 Example3 St", "Bagong Pag-asa"],
//         country: "Philippines",
//         region: "NCR",
//         province: "Metro Manila",
//         city: "Quezon City",
//         district: "5th District",
//         barangay: "Bagong Pag-asa",
//         street: "Example3 St",
//         purok: "Purok 6",
//         sitio: "Sitio Example3",
//         overpass: [["overpass 7", "overpass 8"]],
//         long: 120.9876,
//         lat: 14.5995,
//         zipcode: "1000",
//         postalCode: "1000",
//         period: {
//           start: "2014-03-03",
//           end: "2024-12-31",
//         },
//       },
//     ],
//     contact: "+639181234569",
//     email: "jose.rizal@example.com",
//     birthday: "1970-03-03",
//     age: 54,
//     sex: "male",
//     status: "inactive",
//     role: "viewer",
//     type: "member",
//     category: "voter",
//   },
//   {
//     id: "3",
//     customId: "PH-2024-0003",
//     precinct: {
//       id: "precinct-003",
//       name: "Precinct 3",
//       adress: [
//         {
//           use: "work",
//           type: "physical",
//           text: "Community Center, Bagong Pag-asa, Manila, Metro Manila, Philippines",
//           line: ["Community Center", "Bagong Pag-asa"],
//           country: "Philippines",
//           region: "NCR",
//           province: "Metro Manila",
//           city: "Manila",
//           district: "5th District",
//           barangay: "Bagong Pag-asa",
//           street: "Main St",
//           purok: "Purok 5",
//           sitio: "Sitio Example3",
//           overpass: [["overpass 5", "overpass 6"]],
//           long: 120.9876,
//           lat: 14.5995,
//           zipcode: "1000",
//           postalCode: "1000",
//           period: {
//             start: "2014-03-03",
//             end: "2024-12-31",
//           },
//         },
//       ],
//       cluster: "Cluster C",
//     },
//     photo: "",
//     name: {
//       firstname: "Kent",
//       lastname: "Piolo",
//       middlename: "Pascual",
//       suffix: "",
//       prefix: "Engr.",
//       degree: "",
//     },
//     address: [
//       {
//         use: "home",
//         type: "physical",
//         text: "789 Example3 St, Alicia, Manila, Metro Manila, Philippines",
//         line: ["789 Example3 St", "Alicia"],
//         country: "Philippines",
//         region: "NCR",
//         province: "Metro Manila",
//         city: "Quezon City",
//         district: "5th District",
//         barangay: "Alicia",
//         street: "Example3 St",
//         purok: "Purok 6",
//         sitio: "Sitio Example3",
//         overpass: [["overpass 7", "overpass 8"]],
//         long: 120.9876,
//         lat: 14.5995,
//         zipcode: "1000",
//         postalCode: "1000",
//         period: {
//           start: "2014-03-03",
//           end: "2024-12-31",
//         },
//       },
//     ],
//     contact: "+639181234569",
//     email: "jose.rizal@example.com",
//     birthday: "1970-03-03",
//     age: 54,
//     sex: "male",
//     status: "inactive",
//     role: "viewer",
//     type: "member",
//     category: "voter",
//   },
//   {
//     id: "3",
//     customId: "PH-2024-0003",
//     precinct: {
//       id: "precinct-003",
//       name: "Precinct 3",
//       adress: [
//         {
//           use: "work",
//           type: "physical",
//           text: "Community Center, Bagong Pag-asa, Manila, Metro Manila, Philippines",
//           line: ["Community Center", "Bagong Pag-asa"],
//           country: "Philippines",
//           region: "NCR",
//           province: "Metro Manila",
//           city: "Quezon City",
//           district: "5th District",
//           barangay: "Bagong Pag-asa",
//           street: "Main St",
//           purok: "Purok 5",
//           sitio: "Sitio Example3",
//           overpass: [["overpass 5", "overpass 6"]],
//           long: 120.9876,
//           lat: 14.5995,
//           zipcode: "1000",
//           postalCode: "1000",
//           period: {
//             start: "2014-03-03",
//             end: "2024-12-31",
//           },
//         },
//       ],
//       cluster: "Cluster C",
//     },
//     photo: "",
//     name: {
//       firstname: "Gabriel",
//       lastname: "Great",
//       middlename: "The",
//       suffix: "",
//       prefix: "Engr.",
//       degree: "",
//     },
//     address: [
//       {
//         use: "home",
//         type: "physical",
//         text: "789 Example3 St, Alicia, Manila, Metro Manila, Philippines",
//         line: ["789 Example3 St", "Alicia"],
//         country: "Philippines",
//         region: "NCR",
//         province: "Metro Manila",
//         city: "Quezon City",
//         district: "5th District",
//         barangay: "Alicia",
//         street: "Example3 St",
//         purok: "Purok 6",
//         sitio: "Sitio Example3",
//         overpass: [["overpass 7", "overpass 8"]],
//         long: 120.9876,
//         lat: 14.5995,
//         zipcode: "1000",
//         postalCode: "1000",
//         period: {
//           start: "2014-03-03",
//           end: "2024-12-31",
//         },
//       },
//     ],
//     contact: "+639181234569",
//     email: "jose.rizal@example.com",
//     birthday: "1970-03-03",
//     age: 54,
//     sex: "male",
//     status: "inactive",
//     role: "viewer",
//     type: "member",
//     category: "voter",
//   },
// ];

// export const sampleVotes: Election[] = [
//   {
//     id: "election-2024-001",
//     name: "Presidential Election 2024",
//     photo: ["photo1.jpg", "photo2.jpg"],
//     coverPhoto: "coverPhoto.jpg",
//     category: "presidential",
//     startDate: "2024-11-03T08:00:00.000Z",
//     endDate: "2024-11-04T18:00:00.000Z",
//     status: "ongoing",
//     votes: [
//       {
//         id: "vote-2024-001",
//         personId: "0",
//         precinctId: "precinct-001",
//         date: "2024-11-03",
//         startTime: "08:00:00",
//         endTime: "08:15:00",
//         status: "cast",
//       },
//       {
//         id: "vote-2024-002",
//         personId: "1",
//         precinctId: "precinct-002",
//         date: "2024-11-03",
//         startTime: "08:30:00",
//         endTime: "08:45:00",
//         status: "pending",
//       },
//     ],
//   },
//   {
//     id: "election-2024-002",
//     name: "Local Election 2024",
//     photo: ["localPhoto1.jpg", "localPhoto2.jpg"],
//     coverPhoto: "localCoverPhoto.jpg",
//     category: "local",
//     startDate: "2024-10-01T08:00:00.000Z",
//     endDate: "2024-10-01T18:00:00.000Z",
//     status: "completed",
//     votes: [
//       {
//         id: "vote-2024-003",
//         personId: "0",
//         precinctId: "precinct-003",
//         date: "2024-10-01",
//         startTime: "09:00:00",
//         endTime: "09:10:00",
//         status: "cast",
//       },
//       {
//         id: "vote-2024-004",
//         personId: "1",
//         precinctId: "precinct-004",
//         date: "2024-10-01",
//         startTime: "09:30:00",
//         endTime: "09:40:00",
//         status: "rejected",
//       },
//     ],
//   },
// ];
