import { Field } from "../models/fieldModels";

export const PERSON_FIELD: Field[] = [
  {
    name: "Name",
    type: "singletext",
    category: "name",
    option: [],
    required: true,
  },
  {
    name: "Email",
    type: "singletext",
    category: "email",
    option: [],
    required: true,
  },
  {
    name: "Phone",
    type: "singletext",
    category: "phone",
    option: [],
    required: false,
  },
  {
    name: "Status",
    type: "singleselect",
    category: "status",
    option: [],
    required: false,
  },
  {
    name: "Location",
    type: "object",
    category: "location",
    option: [],
    required: false,
  },
  {
    name: "Location",
    type: "object",
    category: "location",
    option: [],
    required: false,
  },
  {
    name: "Person",
    type: "singletext",
    category: "person",
    option: [],
    required: false,
  },
  {
    name: "Group",
    type: "singletext",
    category: "group",
    option: [],
    required: false,
  },
];

export const ATTENDACE_FIELD: Field[] = [
  {
    name: "Id",
    type: "singletext",
    category: "id",
    option: [],
    required: false,
  },
  {
    name: "Ticket No",
    type: "singletext",
    category: "ticketno",
    option: [],
    required: false,
  },
  {
    name: "Full Name",
    type: "singletext",
    category: "fullname",
    option: [],
    required: false,
  },
  {
    name: "Code Name",
    type: "singletext",
    category: "codename",
    option: [],
    required: false,
  },
  {
    name: "First Name",
    type: "singletext",
    category: "name",
    option: [],
    required: false,
  },
  {
    name: "Last Name",
    type: "singletext",
    category: "lastname",
    option: [],
    required: false,
  },
  {
    name: "Middle Name",
    type: "singletext",
    category: "middlename",
    option: [],
    required: false,
  },
  {
    name: "Middle Initial",
    type: "singletext",
    category: "middleinitial",
    option: [],
    required: false,
  },
  {
    name: "Suffix",
    type: "singletext",
    category: "suffix",
    option: [],
    required: false,
  },
  {
    name: "Rank",
    type: "singletext",
    category: "rank",
    option: [],
    required: false,
  },
  {
    name: "Group",
    type: "multiselect",
    category: "group",
    option: [],
    required: false,
  },
  {
    name: "Status",
    type: "singleselect",
    category: "status",
    option: [],
    required: false,
  },
  {
    name: "Location",
    type: "object",
    category: "location",
    option: [],
    required: false,
  },

  {
    name: "Time In",
    type: "time",
    category: "timein",
    option: [],
    required: false,
  },
  {
    name: "Time Out",
    type: "time",
    category: "timeout",
    option: [],
    required: false,
  },
  {
    name: "Date",
    type: "date",
    category: "date",
    option: [],
    required: false,
  },
  {
    name: "Duration",
    type: "calculated",
    category: "duration",
    option: [],
    required: false,
  },
  {
    name: "Notes",
    type: "multitext",
    category: "notes",
    option: [],
    required: false,
  },
];
